-- Ecommerce Sales Project

-- Create Database
Create Database ecommerce_project;

-- Use Database
Use ecommerce_project;

CREATE TABLE customers (
    customer_id INT,
    customer_name VARCHAR(100),
    email VARCHAR(100),
    city VARCHAR(50),
    country VARCHAR(50),
    loyalty_status VARCHAR(20)
);

describe customers;

CREATE TABLE products (
    product_id INT,
    product_name VARCHAR(100),
    category VARCHAR(50),
    price FLOAT,
    stock_quantity INT
);

describe products;

CREATE TABLE orders (
    order_id INT,
    customer_id INT,
    product_id INT,
    order_date DATETIME,
    quantity INT,
    total_amount FLOAT,
    payment_method VARCHAR(50),
    order_status VARCHAR(50)
);

describe orders;

-- DATA HAS BEEN IMPORTED
SELECT * FROM customers;
SELECT * FROM products;
SELECT * FROM orders;

-- ADD PRIMARY KEY

ALTER TABLE customers 
ADD PRIMARY KEY (customer_id);

ALTER TABLE productS 
ADD PRIMARY KEY (product_id);

ALTER TABLE orders 
ADD PRIMARY KEY (order_id);


-- CONNECT CUSTOMERS TO ORDERS (APPLY FK)
ALTER TABLE orders
ADD CONSTRAINT fk_customer
FOREIGN KEY (customer_id)
REFERENCES customers(customer_id);

-- CONNECT PRODUCT TO ORDERS (FK)
ALTER TABLE orders
ADD CONSTRAINT fk_product
FOREIGN KEY (product_id)
REFERENCES products(product_id);


-- This query joins customers, orders, and products tables
-- to display combined relational data using INNER JOIN.
-- It shows how each order is linked to a specific customer and product.
SELECT 
o.order_id,
c.customer_id,
p.product_id
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
JOIN products p ON o.product_id = p.product_id;


-- Count total number of orders placed by each customer
-- This query groups data by customer_id and counts order_id
SELECT 
c.customer_id,
COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o 
ON c.customer_id = o.customer_id
GROUP BY c.customer_id
ORDER BY total_orders DESC;


-- Calculate total revenue generated by each product
-- Using total_amount column from orders table
SELECT 
p.product_id,
SUM(o.total_amount) AS total_revenue
FROM orders o
JOIN products p 
ON o.product_id = p.product_id
GROUP BY p.product_id
ORDER BY total_revenue DESC;


-- Identify top customers based on total spending
-- This query sums total_amount for each customer
SELECT 
c.customer_id,
SUM(o.total_amount) AS total_spent
FROM customers c
JOIN orders o 
ON c.customer_id = o.customer_id
GROUP BY c.customer_id
ORDER BY total_spent DESC;


-- Calculate monthly sales trend
-- Groups total revenue by year and month from order_date
SELECT 
YEAR(order_date) AS year,
MONTH(order_date) AS month,
SUM(total_amount) AS monthly_sales
FROM orders
GROUP BY YEAR(order_date), MONTH(order_date)
ORDER BY year,  MONTH(order_date);


-- Analyze number of orders by status
-- Helps understand order distribution and operational performance
SELECT 
order_status,
COUNT(order_id) AS total_orders
FROM orders
GROUP BY order_status
ORDER BY total_orders DESC;


-- Analyze orders and revenue by payment method
-- Helps understand customer payment preferences
SELECT 
payment_method,
COUNT(*) AS total_orders,
SUM(total_amount) AS total_revenue
FROM orders
GROUP BY payment_method;


-- Calculate total revenue for each order status
-- Helps understand how much revenue comes from delivered, cancelled, etc.
SELECT 
order_status,
SUM(total_amount) AS total_revenue
FROM orders
GROUP BY order_status
ORDER BY total_revenue DESC;

-- Top 3 Products by Revenue
SELECT 
p.product_id,
SUM(o.total_amount) AS revenue
FROM orders o
JOIN products p ON o.product_id = p.product_id
GROUP BY p.product_id
ORDER BY revenue DESC
LIMIT 3;

-- Customer Ranking
SELECT 
customer_id,
SUM(total_amount) AS total_spent,
RANK() OVER (ORDER BY SUM(total_amount) DESC) AS rank_position
FROM orders
GROUP BY customer_id;


-- Customer Ranking 2
SELECT 
customer_id,
SUM(total_amount) AS total_spent,
RANK() OVER (ORDER BY SUM(total_amount) DESC) AS rank_position
FROM orders
GROUP BY customer_id;

-- Average Order Value
SELECT 
customer_id,
AVG(total_amount) AS avg_order_value
FROM orders
GROUP BY customer_id;
















